#!/usr/bin/env python3
"""
Gerar `docs/assets/js/data-bundle.js` a partir dos JSONs em `data/`.

Uso:
  python3 generate_bundle.py

Escreve: docs/assets/js/data-bundle.js
"""
import json
from pathlib import Path

ROOT = Path(__file__).parent
DATA_DIR = ROOT / 'data'
OUT_DIR = ROOT / 'docs' / 'assets' / 'js'
OUT_DIR.mkdir(parents=True, exist_ok=True)

# Discover all .json files in data/ (ignore manifest.json)
bundle = {}
for path in sorted(DATA_DIR.glob('*.json')):
    if path.name == 'manifest.json':
        continue
    try:
        with path.open('r', encoding='utf-8') as j:
            arr = json.load(j)
            bundle[path.name] = arr
    except Exception as e:
        print('Erro ao ler', path.name, e)

out_path = OUT_DIR / 'data-bundle.js'
with out_path.open('w', encoding='utf-8') as out:
    out.write('// Generated by generate_bundle.py — do not edit manually\n')
    out.write('window.__GAME_DATA__ = ')
    json.dump(bundle, out, ensure_ascii=False)
    out.write(' ;\n')

print('Gerado', out_path)

# Generate docs/categories/*.md pages and update mkdocs.yml nav
DOCS_DIR = ROOT / 'docs'
CAT_DIR = DOCS_DIR / 'categories'
CAT_DIR.mkdir(parents=True, exist_ok=True)

mkdocs_path = ROOT / 'mkdocs.yml'
nav_entries = [{'Home': 'index.md'}]

for fname in sorted(bundle.keys()):
    title = fname.replace('.json','').replace('-',' ').replace('_',' ').upper()
    slug = fname.replace('.json','')
    page_path = f'categories/{slug}.md'
    # write category page
    with (CAT_DIR / f'{slug}.md').open('w', encoding='utf-8') as p:
        p.write(f'# {title}\n\n')
        p.write(f'<div id="pageCategory" data-file="{fname}"></div>\n\n')
        p.write('<div id="grid" class="grid"></div>\n')
        p.write('<div id="pagination" class="pagination"></div>\n')

    nav_entries.append({title: page_path})

# write mkdocs.yml with nav entries
mk = {
    'site_name': 'Categorias',
    'site_description': 'Arquivo de jogos — visualização por categoria',
    'nav': nav_entries,
    'theme': {'name': 'readthedocs'},
    'extra_css': ['assets/css/style.css'],
    'extra_javascript': ['assets/js/data-bundle.js', 'assets/js/app.js']
}

with mkdocs_path.open('w', encoding='utf-8') as m:
    yaml = []
    yaml.append(f"site_name: {mk['site_name']}")
    yaml.append(f"site_description: {mk['site_description']}")
    yaml.append('nav:')
    for it in mk['nav']:
        for k,v in it.items():
            yaml.append(f"  - {k}: {v}")
    yaml.append('theme:')
    yaml.append(f"  name: {mk['theme']['name']}")
    yaml.append('extra_css:')
    for c in mk['extra_css']:
        yaml.append(f"  - {c}")
    yaml.append('extra_javascript:')
    for j in mk['extra_javascript']:
        yaml.append(f"  - {j}")
    m.write('\n'.join(yaml) + '\n')

print('Atualizado mkdocs.yml com', len(nav_entries)-1, 'categorias')
